### ISSUE TITLE
Marks still shown after :delmarks!

### ISSUE THREAD

**Issue by tmalsburg** [roman/evil-visual-mark-mode#10]
Evil now has support for deleting marks (as in Vim, see [here](https://github.com/emacs-evil/evil/issues/1301)). You can say `:delmarks!` to delete all marks, or `:delmarks a` to delete mark `a`. However, after deleting marks, they are still displayed by evil-visual-marks-mode.

**Comment by Dewdrops** [comment]
Thanks for the feedback. The issue has been fixed in ver 0.0.5
