### ISSUE TITLE
Default background face doesn't work

### ISSUE THREAD

**Issue by Dewdrops** [roman/evil-visual-mark-mode#5]
Here's another issue: the default background face (`color-89`) doesn't work for me.
It seems that `color-89` is not defined in my emacs, I can't find this name in `list-color-display` buffer neither. Don't know why.

Till now I just redefine `evil-visual-mark-face` to bypass this problem, but maybe we can use a more general color as default background face?

**Comment by roman** [comment]
Maybe we can try a hex value instead, the color I use is kind of magenta... I'll work out some of that tomorrow, thanks for your feedback and PR :-)

**Comment by Dewdrops** [comment]
A hex value may be the most robust way.

I found this project on Github just before I writing it myself, though I had no good idea how to properly render the marks without (potentially) affecting other plugins. I think the implementation method `evil-visual-mark-mode` uses (via `before-string` property of overlay) is very clever.
